src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['Email'], message: 'There is already an account with this Email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $Email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): static
    {
        $this->Email = $Email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->Email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
}

templates/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ asset ('uploads/image/ao-product.png') }}">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
{#    <link rel = "stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">#}
    <title>{% block title %}Clothes{% endblock %}</title>
    <link rel="icon" href="../../favicon.ico">
    <link rel="canonical" href="https://getbootstrap.com/docs/3.4/examples/starter-template/">

{#    <title>{% block title %}Welcome!{% endblock %}</title>#}


    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    {% block stylesheets %}{% endblock %}


</head>

<body>

<div class="alert alert-info">
<nav class="navbar navbar">
    <div class="container">
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}s
        <p style="color: white">Hello {{ app.user.email }}!</p>
        {% else %}
        <p style="color: white">Hello anonymous user!</p>
        {% endif %}
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Oversize Shop</a>
        </div>
                <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
        <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
{#                <li class="active"><a href="#">Home</a></li>#}

                <li><a href="{{ path('app_product') }}">Product </a></li>
                <li><a href="{{ path('app_category') }}">Category </a></li>
                <li><a href="{{ path('app_brand') }}">Brand </a></li>
                <li><a href="{{ path('app_login') }}">Login </a></li>
                <li><a href="{{ path('app_register') }}">Register </a></li>
            </ul>
{#            <form class="form-inline my-2 my-lg-0">#}
{#                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#            </form>#}
        </div><!--/.nav-collapse -->
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            {% for flash_message in app.session.flashBag.get('notice') %}
                <div class="alert alert-success">{{ flash_message }}</div>
            {% endfor %}
            {% for flash_message in app.session.flashBag.get('error') %}
                <div class="alert alert-danger">{{ flash_message }}</div>
            {% endfor %}
            {% block body %}{% endblock %}
        </div>
    </div>
</div>


</div><!-- /.container -->
</div>

{% block javascripts %}{% endblock %}

</body>
</html>